version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: e-auction-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eAuction-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
